#!/bin/zsh
# profile file. Runs on login. Environmental variables are set here.


unsetopt PROMPT_SP

# Default programs:
export BROWSER="icecat"
export TERMINAL="st"
export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="less"

# ~/ Clean-up:
export PATH=$PATH:~/.local/bin/statusbar
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export GOPATH="$XDG_DATA_HOME/go"
export LESSHISTFILE="-"

# Other program settings:
export MOZ_ACCELERATED=1
export QT_QPA_PLATFORMTHEME="gtk2"	# Have QT use gtk2 theme
export QT_STYLE_OVERRIDE="kvantum"      # Have QT use kvantum style
export _JAVA_AWT_WM_NONREPARENTING=1	# Fix for Java applications in dwm
export MUSICDIR="$HOME/Music"		# Music directory location
export CM_SELECTIONS="clipboard"	# Make clipmenu copy to clipboard
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
